[package]
name = "jclone"
description = "A command line tool for cloning and organising git repositories"
version = "0.3.1"
edition = "2024"
license = "BSD-3-Clause-No-Military-License"

[dependencies]
toml = "0.9.2"

[dev-dependencies]
rstest = "0.25.0"
