[package]
name = "jclone"
description = "A command line tool for cloning and organising git repositories"
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause-No-Military-License"

[dependencies]
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
