name: Build for MacOS
on:
  push:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Test
      run: cargo test
  build:
    runs-on: macos-latest
    needs: [test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}
    - name: Build release
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      with:
        name: jclone-executable-macos
        path: target/release/jclone
