name: Build & Release
on:
  push:
    tags: v*
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Test
      run: cargo test
  build-macos:
    runs-on: macos-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}
    - name: Build release (MacOS)
      run: |
        cargo build --verbose --release
        zip --junk-paths jclone-macos.zip ./target/release/jclone
    - uses: actions/upload-artifact@v4
      with:
        name: build-macos-zipped
        path: ./jclone-macos.zip
  build-and-release:
    runs-on: ubuntu-latest
    needs: [test, build-macos]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}
    - uses: actions/download-artifact@v5
      with:
        name: build-macos-zipped
        path: target/macos
    - name: Install deps
      run: cargo install cargo-deb cargo-generate-rpm
    - name: Build release
      run: |
        cargo build --verbose --release
        zip --junk-paths ./target/release/jclone-linux-x64.zip ./target/release/jclone
    - name: Package deb
      run: cargo deb
    - name: Package rpm
      run: cargo generate-rpm
    - name: Create GitHub release
      run: |
        # Check files and release
        tag="${{ github.ref_name }}"
        exe="./target/release/jclone-linux-x64.zip"
        exemac="./target/macos/jclone-macos.zip"
        deb=$(find ./target/debian -name "jclone*.deb" -print -quit | grep .)
        rpm=$(find ./target/generate-rpm -name "jclone*.rpm" -print -quit | grep .)
        stat "$exe" "$deb" "$rpm" > /dev/null

        gh release create "$tag" \
          --draft \
          --verify-tag \
          --title "jclone ${tag#v}" \
          --notes-from-tag

        gh release upload "$tag" \
          "$exe#Executable (Linux x64, zipped)" \
          "$exemac#Executable (MacOS, zipped)" \
          "$deb#Installer (.deb for Debian/Ubuntu)" \
          "$rpm#Installer (.rpm for RHEL/Fedora)"
